<a href="https://colab.research.google.com/github/MichalPietruszevski/phd/blob/main/wykluczenia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import openpyxl

# Google colab

In [3]:
from google.colab import drive
drive.mount('/content/drive')
DANE = "/content/drive/MyDrive/DOKTORAT/ANALIZY/DANE/baza_danych_270426.xlsx"
df = pd.read_excel(DANE)

Mounted at /content/drive

# Local

In [5]:
DANE = "../DANE/baza_danych_270426.xlsx"
df = pd.read_excel(DANE)

FileNotFoundError: [Errno 2] No such file or directory: '../DANE/baza_danych_270426.xlsx'

Dobra jakich potrzebujemy kolumn do wykluczen  
Potrzebuje:  
ank_zdro_palenie_teraz   
  
ank_zdro_alko_U  



Do kontroli:  
ank_zwi_tn  
ank_zwi_status
ank_zdro_leki_U  
ank_zdro_chor_przew_tn

In [6]:
# Merge categories for ank_zdro_alko
def categorize_alko(val):
    if pd.isna(val):
        return val
    val_str = str(val).strip().lower()

    # 4 razy w tygodniu i częściej
    if '4 ra' in val_str and 'tygodni' in val_str:
        return '4 razy w tygodniu i częściej'

    # 2-3 razy w tygodniu
    if '2-3 razy w tygodniu' in val_str:
        return '2-3 razy w tygodniu'

    # Raz w miesiącu lub rzadziej (includes "2-4 razy w miesiącu")
    if 'miesiąc' in val_str or 'rzadziej' in val_str:
        return 'raz w miesiącu lub rzadziej'

    # Nigdy
    if 'nigdy' in val_str:
        return 'nigdy'

    # Default for numeric or unclear values
    return 'raz w miesiącu lub rzadziej'

df['ank_zdro_alko_U'] = df['ank_zdro_alko'].apply(categorize_alko)
df.ank_zdro_alko_U.value_counts()

ank_zdro_alko_U
raz w miesiącu lub rzadziej     137
2-3 razy w tygodniu              36
nigdy                            31
4 razy w tygodniu i częściej      6
Name: count, dtype: int64

In [7]:
# Create the ank_zdro_leki_U column with TAK/NIE labels
def categorize_leki(val):
    if pd.isna(val) or str(val).strip() in ['BRAK', '', 'nan']:
        return 'NIE'
    else:
        return 'TAK'

df['ank_zdro_leki_U'] = df['ank_zdro_leki'].apply(categorize_leki)

In [8]:
df.ank_zdro_leki_U.value_counts()

ank_zdro_leki_U
NIE    134
TAK     77
Name: count, dtype: int64

In [9]:
df.ank_zwi_tn.value_counts()

ank_zwi_tn
TAK    185
NIE     24
Name: count, dtype: int64

# Cukrzyca

In [ ]:
for i in df.columns.tolist(): print(i) if i.startswith("ank_zdro") else None

In [21]:
# 1. Rozszerzona funkcja czyszcząca
def clean_choroby_v2(val):
    if pd.isna(val) or str(val).lower().strip() in ['brak', 'nie', 'nie dotyczy', '-', 'nan']:
        return 'Brak'

    s = str(val).lower().strip()

    # Mapowanie i poprawa literówek
    if 'cukrzyca' in s:
        return 'Cukrzyca'

    return s.capitalize()

# 2. Tworzenie nowej zmiennej
df['ank_zdro_chor_przew_cukrz'] = df['ank_zdro_chor_przew_tx'].apply(clean_choroby_v2)

# 3. Sprawdzenie wyników po poprawkach
print("Zaktualizowane kategorie (ank_zdro_chor_przew_U):")
print(df['ank_zdro_chor_przew_cukrz'].value_counts())

Zaktualizowane kategorie (ank_zdro_chor_przew_U):
ank_zdro_chor_przew_cukrz
Brak                                                                                      138
Nadciśnienie                                                                               10
Cukrzyca                                                                                    5
Nadciśnienie od 2 lat                                                                       2
Nadciśnienie 3 lata                                                                         2
Nadciśnienie od 13 lat                                                                      2
Choroba scheuermanna                                                                        1
Nadciśnienie od 20 lat                                                                      1
Niedoczynność tarczycy od 8 lat                                                             1
Nadciśnienie (od 10 lat)                                                                    1
Kamica nerkowa od 30 lat                                                                    1
Przewlekłe zapalenie trzustki od 1983                                                       1
Łysienie plackowate od 6 lat; róża nawrotowa od roku                                        1
Żylaki                                                                                      1
Astma od 20 lat                                                                             1
Nadciśnienie od 4 lat; choroby serca od roku                                                1
Zapalenie kości, choroby serca, naczynioruchowy nieżyt nosa                                 1
Nadciśnienie 8 lat; astma od 45 lat ale znikome objawy                                      1
Nadciśnienie od 2005                                                                        1
Nadciśnienie od 40 lat, cuktrzyca od 10 lat                                                 1
Nadcisnienie od 3 lat                                                                       1
Łuszczyca od roku                                                                           1
Astma                                                                                       1
Dyskopatia od 33 lat                                                                        1
Nadciśnienie od 7 lat                                                                       1
Nadciśnienie od 25 lat                                                                      1
Łuszczyca od 20 lat                                                                         1
Nadciśnienie od 2008                                                                        1
Nadcinienie od 10 lat                                                                       1
Nadciśnienie od 12 lat; pochp od 2019                                                       1
Nadciśnienie od 15 lat                                                                      1
Rzs 5 lat                                                                                   1
Wysoki cholesterol od 8 lat; wada wzroku od urodzenia                                       1
Nadciśnienie od 5 lat                                                                       1
Nadciśnienie od 10 lat                                                                      1
Nadciśnienie 5 lat                                                                          1
Nadciśnienie 8 lat                                                                          1
Pochp od 6 lat                                                                              1
Nadciśnienie 2 lata                                                                         1
Osteoporoza; wrzody od 12 mcy; dyskopatia od 15 lat; zmiany zwyrodnienionwe kręgosłupa      1
Nadciśnienie 8 lat; alergie 15 lat                                                          1
Nadciśnienie od 10 lat; bielactwo od 25 lat                                                 1
Choroba meniera od 34 lat                                                                   1
Nadciśnienie 10 lat                                                                         1
Borelioza 10.2022                                                                           1
Gerd od 18 lat                                                                              1
Lekkie stłuszczenie wątroby od 8 lat                                                        1
Przeziębienia od wielu lat                                                                  1
Nadciśnienie od 6 lat                                                                       1
Dna moczanowa od 26 lat                                                                     1
Dykopatia od 17-18 lat                                                                      1
Polineuropatia od 1 roku                                                                    1
Nadciśnienie od roku, astma od 20 lat                                                       1
Adhd - całe życie                                                                           1
Nadciśnienie, kłębuszkowe zapalenie nerek - od 2001                                         1
Zapalenie kości/stawów od 5 lat                                                             1
Refluks (od 20 lat)                                                                         1
Nadciśnienie (1 rok)                                                                        1
Name: count, dtype: int64

TODO:  
[] ogarnąć choroby uprościć  
[] ogarnać leki na cukrzycę  
[] ogarnąć hemoglobinę glikowaną

'par_hg_glikowana_mol' - poniżej 5,7% (39 mmol/mol).
'par_ob' - U mężczyzn w wieku 15–50 lat OB powinno być mniejsze niż 15 mm/h, a powyżej 50 roku życia ten zakres wzrasta, niemniej nie powinien być wyższy niż 20 mm/h

In [29]:
import pandas as pd

# Konwersja kolumn na format numeryczny
df['par_hg_glikowana_mol'] = pd.to_numeric(df['par_hg_glikowana_mol'], errors='coerce')
df['par_ob'] = pd.to_numeric(df['par_ob'], errors='coerce')

# 1. Hemoglobina glikowana - norma poniżej 39 mmol/mol
def check_hg_norm(val):
    if pd.isna(val): return None
    return 1 if val < 39 else 0

df['par_hg_glikowana_norma'] = df['par_hg_glikowana_mol'].apply(check_hg_norm)

# 2. OB (Odczyn Biernackiego) - traktujemy wszystkich jako > 50 lat
def check_ob_norm_v2(val):
    if pd.isna(val): return None
    # Norma dla osób > 50 roku życia: < 20 mm/h
    return 1 if val < 20 else 0

df['par_ob_norma'] = df['par_ob'].apply(check_ob_norm_v2)

# Wyświetlenie podsumowania
print("Podsumowanie norm dla Hemoglobiny Glikowanej (norma < 39):")
print(df['par_hg_glikowana_norma'].value_counts(dropna=False))
print("\nPodsumowanie norm dla OB (wszyscy jako >50 lat, norma < 20):")
print(df['par_ob_norma'].value_counts(dropna=False))

display(df[['par_hg_glikowana_mol', 'par_hg_glikowana_norma', 'par_ob', 'par_ob_norma']].head(10))

Podsumowanie norm dla Hemoglobiny Glikowanej (norma < 39):
par_hg_glikowana_norma
1.0    161
0.0     49
NaN      1
Name: count, dtype: int64

Podsumowanie norm dla OB (wszyscy jako >50 lat, norma < 20):
par_ob_norma
1.0    179
0.0     31
NaN      1
Name: count, dtype: int64

   par_hg_glikowana_mol  par_hg_glikowana_norma  par_ob  par_ob_norma
0                  35.1                     1.0     5.0           1.0
1                  36.7                     1.0     6.0           1.0
2                  35.4                     1.0     3.0           1.0
3                  38.0                     1.0     5.0           1.0
4                  32.9                     1.0     2.0           1.0
5                  34.0                     1.0     2.0           1.0
6                  35.4                     1.0     5.0           1.0
7                  34.1                     1.0     4.0           1.0
8                  42.9                     0.0    23.0           0.0
9                  37.2                     1.0     4.0           1.0

In [25]:
import re

# Zaktualizowana lista słów kluczowych o Galvus i fragmenty łapiące literówki
diabetes_keywords = ['metform', 'glucophag', 'siofor', 'siofou', 'insulina', 'jardiance', 'forxiga', 'victoza', 'ozempic', 'rybelsus', 'amaryl', 'diaprel', 'gliclada', 'galvus']

def check_diabetes_meds(val):
    if pd.isna(val):
        return 0
    s = str(val).lower()
    if any(keyword in s for keyword in diabetes_keywords):
        return 1
    return 0

# Tworzenie/Aktualizacja kolumny
df['ank_zdro_leki_cukrzyca_D'] = df['ank_zdro_leki'].apply(check_diabetes_meds)

# Wyświetlenie osób po aktualizacji
print("Osoby zidentyfikowane jako przyjmujące leki na cukrzycę:")
display(df[df['ank_zdro_leki_cukrzyca_D'] == 1][['ank_zdro_leki', 'ank_zdro_leki_cukrzyca_D']])

print("\nPodsumowanie nowej kolumny dummy:")
print(df['ank_zdro_leki_cukrzyca_D'].value_counts())

Osoby zidentyfikowane jako przyjmujące leki na cukrzycę:

,ank_zdro_leki,ank_zdro_leki_cukrzyca_D
57,Lorista H 1/2x50 mg; Betaloc 20K 1/2x 95mg; Fo...,1
72,Comlessa 8+10+250; Nobilet; SioFou 850,1
112,"Glucophag, Prestarium 5mg. Romazic, Milurit 100mg",1
121,"Medal, tolura, milurit, romazic, ozempic",1
180,"Metformax, galvus, amaryl",1

Podsumowanie nowej kolumny dummy:
ank_zdro_leki_cukrzyca_D
0    206
1      5
Name: count, dtype: int64

```markdown
### Przegląd wszystkich leków w kolumnie `ank_zdro_leki`  
Poniższy kod wyciągnie unikalne wpisy, aby sprawdzić, czy nie pominęliśmy żadnych leków na cukrzycę lub innych istotnych substancji.
```

In [24]:
# Wyciągnięcie unikalnych wpisów leków, posortowanych alfabetycznie
all_meds = df['ank_zdro_leki'].dropna().unique().tolist()
all_meds_cleaned = sorted(list(set([str(m).strip() for m in all_meds])))

print(f"Liczba unikalnych wpisów: {len(all_meds_cleaned)}")
print("--- Lista wszystkich wpisów w 'ank_zdro_leki' ---")
for med in all_meds_cleaned:
    print(med)

Liczba unikalnych wpisów: 77
--- Lista wszystkich wpisów w 'ank_zdro_leki' ---
Acar, zahron duo, co-prestarium, bisovation, dalfor uno, polomag B6, nefrocal, prostaceum
Adatam, lipanthyl odstawiony rok temu
Amlessa
Amlozeh, zahron
Atrox
BEtaloc, Flixonase
BRAK
Betalol, Tritace
Betaserc
Betozic, Trutace, Jovesto, Acard, Melatonina 5G
Bisocard, Valsacor, Omnilocas
Candezek Combi 8/5
Carzap, hitaxa
Cetryzyna okresowo
Co-Amlessa (4+5+1,25); Kalipoz; Neomag skurcz; Prostamol uno
Co-Amlessa 8mg+5mg+2,5mg
Co-prenesse, esseliv forte
Co-prestarium 10 mg+10 mg
Co-prestarium 5mg+5 mg, contrahist
Comlessa 8+10+250; Nobilet; SioFou 850
Concor, tertensif
Controloc 20
Dipperam 5 mg + 70mg
Elicea 10 mg
Euthyrox 88
Ezehron Duo, polprazol pph, polpril, tritace 5  Ezehron Duo, polprazol pph, polpril, tritace 5
Flonidan, aerozole do nosa, witaminy D3, C, rutyna, magnez
Fostex, telmizek
Glucophag, Prestarium 5mg. Romazic, Milurit 100mg
Indapen, trittico
Indix combi, nebilet, amlopin, atoris
Klatra, monkasta
Lipancrea
Lipiforma, 4fllex, hylo comod
Loratadyna
Lorista
Lorista H 1/2x50 mg; Betaloc 20K 1/2x 95mg; Forxiga 10 mg; Glucophage x R 50 mg
Medal, tolura, milurit, romazic, ozempic
Medikinet CR 20 mg od 01/2023
Metformax, galvus, amaryl
Milurit
Momester
NIE
Nebilet, karbis
Nebilet, nolipret, tulip, aspiryna bay 75mg
Noliprel Biforte 10mg + 2 mg; Atoris 10 mg; cartexn 2x 400 mg; momestfr 50mg x 2; Acard 75 mg
Nolpoza (20 mg); Zirid (50 mg). Oba od 2 tygodni.
Noviprel Forte
Polpril, acard, areplex, rustox, nebicard
Polpril, atoris
Polsart, Sobycor, Indapen, lacipil
Prestarium
Prestarium 5 mg
Prostilol 10 mg+5 mg; Neurovit 100 mg+200 mg+0,5 mg
Purethal, lipiforma plus
Ridlip 5 mg; Prosti men, rutinacea max D3
Rimal
Rimal 5 mg+5 mg
Roswera 10 mg
Rupafin
SYM ????
Soldevol 1 raz w miesiącu
Telfexo - w czasie ekspozycji na alergeny
Telmisarfen
Telmisartan
Telmix
Telmizek
Tertengif, Prestilol 5mg + 5mg Transtec35ug- plastrybuprenorphinum i CBD
Tertens-am 1,5 mg
Tezeo HCT 40 mg + 12,5 mg
Trittico CR
Uprox, Tertensif combi
Ursofalk 250mg + co drugi dzień na cholesterol
Vessel Due F, Clatra
Vigantolete 1000x3
Zahron 10mg; Adatam 0,4 mg; Lipanthyl 200 m
Zahron od 26.11.2022 + ???

In [27]:
df.columns.tolist()

['Unnamed: 0',
 'id',
 'hig_sub_oc_zebow',
 'hig_sub_oc_zebow_dych',
 'hig_sub_oc_dziasel',
 'hig_sub_oc_dziasel_dych',
 'hig_kiedy_myje_zeby',
 'hig_myje_zeby_od_razu_po_przebudzeniu',
 'hig_myje_zeby_przed_polożeniem_się_spać',
 'hig_myje_zeby_po_każdym_dużym_posilku',
 'hig_myje_zeby_przed_wyjściem_z_domu',
 'hig_myje_zeby_po_każdej_przekąsce',
 'hig_szczotka',
 'hig_szczotka_U',
 'hig_plyn_plukanie',
 'hig_plyn_plukanie_U',
 'hig_nic_dent',
 'hig_nic_dent_U',
 'hig_mycia_zebow',
 'hig_mycia_zebow_U',
 'hig_mycia_zebow_zmiana',
 'hig_mycia_zebow_zmiana_kiedy',
 'hig_mycia_zebow_przeszlosc',
 'hig_wiz_stoma_przeg',
 'hig_wiz_stoma_przeg_zmiana',
 'hig_wiz_stoma_przeg_zmiana_kiedy',
 'hig_wiz_stoma_przeg_zmiana_przeszlosc',
 'hig_wiz_stoma_inter',
 'hig_wiz_stoma_inter_zmiana',
 'hig_wiz_stoma_inter_zmiana_kiedy',
 'hig_wiz_stoma_inter_zmiana_przeszlosc',
 'hig_jedz_slodycz_teraz',
 'hig_jedz_slodkie_napoje_teraz',
 'hig_jedz_owoce_teraz',
 'hig_jedz_slodka_kawa_teraz',
 'hig_jedz_slodka_guma_teraz',
 'hig_jedz_slodycz_20-40',
 'hig_jedz_slodkie_napoje_20-40',
 'hig_jedz_owoce_20-40',
 'hig_jedz_slodka_kawa_20-40',
 'hig_jedz_slodka_guma_20-40',
 'hig_zab_piaskowanie',
 'hig_zab_usu_kamienia',
 'hig_zab_polerowanie',
 'hig_zab_lakierowanie',
 'hig_zab_wybielanie',
 'hig_zab_fluoryzacja',
 'hig_zab_inne_tn',
 'hig_zab_inne_tx',
 'hig_chor_hipoplazja',
 'hig_chor_paradontoza',
 'hig_chor_bruksizm',
 'hig_chor_wad_zgryzu',
 'hig_chor_inne_tn',
 'hig_chor_inne_tx',
 'pom_wys_ciala_1',
 'pom_wys_ciala_2',
 'pom_wys_kolan_1',
 'pom_wys_kolan_2',
 'pom_obw_szyji_1',
 'pom_obw_szyji_2',
 'pom_obw_brzuch_1',
 'pom_obw_brzuch_2',
 'pom_obw_bioder_1',
 'pom_obw_bioder_2',
 'pom_obw_klatki_1',
 'pom_obw_klatki_2',
 'pom_sze_ramion_1',
 'pom_sze_ramion_2',
 'pom_sze_bioder_1',
 'pom_sze_bioder_2',
 'pom_sze_twarzy_1',
 'pom_sze_twarzy_2',
 'pom_sze_zuchwy_1',
 'pom_sze_zuchwy_2',
 'pom_wys_twarzy_1',
 'pom_wys_twarzy_2',
 'pom_wys_twarzy_fwhr_1',
 'pom_wys_twarzy_fwhr_2',
 'pom_obw_ram_p_1',
 'pom_obw_ram_p_2',
 'pom_obw_ram_l_1',
 'pom_obw_ram_l_2',
 'pom_fald_podlop_p_1',
 'pom_fald_podlop_p_2',
 'pom_fald_podlop_l_1',
 'pom_fald_podlop_l_2',
 'pom_fald_ram_p_1',
 'pom_fald_ram_p_2',
 'pom_fald_ram_l_1',
 'pom_fald_ram_l_2',
 'pom_sila_reka_p_1',
 'pom_sila_reka_p_2',
 'pom_sila_reka_l_1',
 'pom_sila_reka_l_2',
 'pom_sila_grzebiet_1',
 'pom_sila_grzebiet_2',
 'pom_sila_uwagi',
 'pom_sze_nadgar_p_1',
 'pom_sze_nadgar_p_2',
 'pom_sze_nadgar_l_1',
 'pom_sze_nadgar_l_2',
 'pom_pal_p_2_1',
 'pom_pal_p_2_2',
 'pom_pal_l_2_1',
 'pom_pal_l_2_2',
 'pom_pal_p_3_1',
 'pom_pal_p_3_2',
 'pom_pal_l_3_1',
 'pom_pal_l_3_2',
 'pom_pal_p_4_1',
 'pom_pal_p_4_2',
 'pom_pal_l_4_1',
 'pom_pal_l_4_2',
 'pom_pal_p_5_1',
 'pom_pal_p_5_2',
 'pom_pal_l_5_1',
 'pom_pal_l_5_2',
 'pom_pal_uwagi',
 'recznosc',
 'par_ABI_L',
 'par_ABI_P',
 'par_cis_skurcz',
 'par_cis_rozkurcz',
 'par_puls',
 'ank_data_badania',
 'rmr',
 'invied',
 'uwagi',
 'ank_data_urodzenia',
 'ank_wiek_miesiace',
 'ank_wiek_lata',
 'ank_miej_urodzenia',
 'ank_miej_zam_tx',
 'ank_miej_zam_kat',
 'ank_miej_zam_wczesniej_1',
 'ank_miej_zam_wczesniej_2',
 'ank_miej_zam_wczesniej_3',
 'ank_miej_zam_wczesniej_4',
 'ank_miej_zam_za_granica',
 'ank_urodz_dane_uwagi',
 'ank_urodz_masa',
 'ank_urodz_dlug',
 'ank_urodz_obw',
 'ank_urodz_tydz',
 'ank_urodz_tydz_kat',
 'ank_urodz_typ_porodu',
 'ank_prac_wyksztalcenie',
 'ank_prac_stat_zawodowy',
 'ank_prac_zawod_wykonywany',
 'ank_prac_rodzaj',
 'ank_prac_kiero',
 'ank_kon_z_sub_szkod',
 'ank_kon_z_sub_szkod_tx',
 'ank_woj_kwalif',
 'ank_woj_rodz_sluz',
 'ank_woj_kat',
 'ank_czas_wol_mlody',
 'ank_czas_wol_teraz',
 'ank_rodzen',
 'ank_rodzen_licz_braci',
 'ank_rodzen_rok_ur_braci',
 'ank_rodzen_licz_siostr',
 'ank_rodzen_rok_ur_siostr',
 'ank_kolej_urodz',
 'ank_rodzen_smierc_1',
 'ank_rodzen_smierc_2',
 'ank_rodzice_matka_data_ur',
 'ank_rodzice_ojeciec_data_ur',
 'ank_rodzice_matka_wiek_gdy_urodzil',
 'ank_rodzice_ojciec_wiek_gdy_urodzil',
 'ank_rodzice_matka_smierc',
 'ank_rodzice_matka_smierc_przyczyna',
 'ank_rodzicie_ojciec_smierc',
 'ank_rodzice_ojciec_smierc_przyczyn',
 'ank_rodzice_syt_mat_w_dziecins',
 'ank_rodzice_rozstanie_tn',
 'ank_rodziec_rozstanie_kiedy',
 'ank_rodzice_opiekun',
 'ank_dziecinstwo_miej_zam',
 'ank_dziecinstwo_sub_chor',
 'ank_dziecinstwo_sub_wys',
 'ank_dziecinstwo_sub_mas',
 'ank_dziecinstwo_temp_dojrzewania',
 'ank_zdro_alergie',
 'ank_zdro_alergie_jakie',
 'ank_zdro_alergie_objawy',
 'ank_zdro_inf_drog_oddech',
 'ank_zdro_chor_przew_tn',
 'ank_zdro_chor_przew_tx',
 'ank_zdro_leki',
 'ank_zdro_por_spec_tn',
 'ank_zdro_por_spec_tx',
 'ank_zdro_szpital',
 'ank_zdro_cze_lekarz',
 'ank_zdro_cze_lekarz_spec',
 'ank_zdro_odd_krew',
 'ank_zdro_papierosy_kiedys',
 'ank_zdro_papierosy_teraz',
 'ank_zdro_papierosy_ile',
 'ank_zdro_papierosy_kiedy_przestal',
 'ank_zdro_alko',
 'ank_zdro_uzalezniony',
 'ank_zdro_alko_upija',
 'ank_zdro_alko_48h',
 'ank_zdro_alko_24h',
 'ank_syt_mat_sub',
 'ank_syt_mat_netto',
 'ank_syt_mat_nie_mart_o_rach',
 'ank_syt_mat_moge_kupic_co_chce',
 'ank_syt_mat_nie_mart_o_rach_przyszlosc',
 'ank_stres_prac',
 'ank_stres_poza_prac',
 'ank_dieta',
 'ank_dieta_od_kiedy',
 'ank_dieta_wykluczenia',
 'ank_dieta_suple_tn',
 'ank_dieta_suple_tx',
 'ank_dieta_suple_cze',
 'ank_zdro_leki_horm',
 'ank_zdro_leki_2dni',
 'ank_sport_regul',
 'ank_sport_regul_info',
 'ank_sport_zimowe',
 'ank_sport_wodne',
 'ank_sport_ekstremalne_przeslosc',
 'ank_sport_ekstremalne_obecnie',
 'ank_sport_przeslosc',
 'ank_zwi_tn',
 'ank_zwi_status',
 'ank_zwi_czas_z_part',
 'ank_dzieci_tn',
 'ank_dzieci_synowie_licz',
 'ank_dzieci_synowie_daty_uro',
 'ank_dzieci_corki_licz',
 'ank_dzieci_corki_daty_uro',
 'ank_dzieci_wszy_z_ta_sama_partnerka_tn',
 'ank_dzieci_zdrowie',
 'ank_dzieci_czy_chce_jak_nie_ma',
 'ank_dzieci_ile_chce',
 'ank_dzieci_czy_chce_wiecej',
 'ank_dzieci_do_jakiego_wieku_utrzym_corka',
 'ank_dzieci_do_jakiego_wieku_utrzym_syn',
 'ank_dzieci_ile_wnukow_chce',
 'ank_dzieci_podz_opiek_matka',
 'ank_dzieci_podz_opiek_ojciec',
 'ank_zwi_wiek_gdy_slub',
 'ank_zwi_wiek_gdy_poznal_partnerke',
 'ank_zwi_po_jakim_czasie_slub',
 'ank_zwi_wiek_inicj_seks',
 'ank_zwi_liczba',
 'ank_zwi_ile_zon',
 'ank_zwi_ile_zarecz',
 'ank_zwi_ile_part_seks',
 'ank_zwi_ile_part_seks_ost_roku',
 'ank_zwi_orientacja',
 'ank_zwi_part_atrak',
 'ank_zwi_part_data_ur',
 'ank_sub_atrak',
 'ank_sub_sila',
 'ank_sub_sila_spadek',
 'ank_sub_pewnosc_w_kontak',
 'ank_sub_zdrowia_stan',
 'ank_sub_zdrowia_spadek',
 'ank_sub_odpornosc',
 'ank_sub_wysilek_w_zdrowie',
 'ank_sub_szansa_na_75_lat_max_wysilek',
 'ank_sub_szansa_na-75_lat_min_wysilek',
 'ank_sen_sredni_czas',
 'ank_sen_problemy',
 'ank_sen_tabletki',
 'ank_sen_budzenie',
 'ank_sen_jakosc',
 'ank_dieta_ostatni_posilek',
 'ank_zdro_chor_w_ost_mies',
 'ank_zdro_chor_w_ost_mies_kiedy_minely_objawy',
 'ank_zdro_opalenie_kiedy_ostatnio',
 'ank_prac_slonce',
 'ank_zdro_cze_opalanie',
 'ank_zdro_chor_covid_tn',
 'ank_zdro_chor_covid_kiedy',
 'ank_zdro_chor_covid_objawy',
 'ank_zdro_chor_covid_szczep_tn',
 'ank_zdro_chor_covid_szczep_powod',
 'ank_sub_drabina_dobrego_zycia',
 'par_usg_stopa_l_young',
 'par_usg_stopa_l_t_score',
 'par_usg_stopa_l_age_matched',
 'par_usg_stopa_l_z_score',
 'par_usg_stopa_p_young',
 'par_usg_stopa_p_t_score',
 'par_usg_stopa_p_age_matched',
 'par_usg_stopa_p_z_score',
 'par_dekl_masa',
 'par_dekl_wys',
 'par_wbc',
 'par_rbc',
 'par_hgb',
 'par_hct',
 'par_mcv',
 'par_mch',
 'par_mchc',
 'par_plt',
 'par_rdw_sd',
 'par_rdw_cv',
 'par_pdw',
 'par_mpv',
 'par_p_lcr',
 'par_pct',
 'par_neutrofile_l_bezw',
 'par_limfocyty_l_bezw',
 'par_monocyty_l_bezw',
 'par_eozynofile_l_bezw',
 'par_bazofile_l_bezw',
 'par_niedojrzale_granulocyty_l_bezw',
 'par_neutrofile_proc',
 'par_limfocyty_proc',
 'par_monocyty_proc',
 'par_eozynofile_proc',
 'par_bazofile_proc',
 'par_niedojrzale_granulocyty_proc',
 'par_nrbc',
 'par_ob',
 'par_fibrynogen',
 'par_hg_glikowana_proc',
 'par_hg_glikowana_mol',
 'par_sars_igg',
 'par_sars_igm',
 'par_wit_d3',
 'par_sod',
 'par_potas',
 'par_wapn',
 'par_magnez',
 'par_alt',
 'par_ast',
 'par_mocznik',
 'par_kreatynina',
 'par_egfr',
 'par_kw_moczowy',
 'par_glukoza',
 'par_choles_cal',
 'par_choles_hdl',
 'par_choles_nie_hdl',
 'par_choles_ldl',
 'par_choles_triglicerid',
 'par_d_dimery',
 'par_prokalcytonina',
 'par_homocysteina',
 'par_tsh',
 'par_estradiol',
 'par_testosteron_ng_dl',
 'par_somatotropina',
 'par_parathormon',
 'par_insulina',
 'par_psa',
 'par_testosteron_wolny_pg_ml',
 'par_igf_1',
 'par_kalcytonina',
 'par_osteokalcyna',
 'par_ppj_ana',
 'wiz_II_data',
 'wiz_II_infekcje_tn',
 'wiz_II_infekcje_kiedy_minely_objawy',
 'wiz_II_leki_ostatnie_miesiac',
 'ank_sub_miejsce_w_rozwoju',
 'ank_sub_drabina_w_dziecinstwie',
 'ank_sub_drabina_30_lat',
 'ank_sub_drabina_obecnie',
 'par_rmr_cosmed',
 'par_seca_masa_tluszcz_kg',
 'par_seca_masa_tluszcz_proc',
 'par_seca_wsk_masy_tluszcz_kg_m2',
 'par_seca_masa_beztluszcz_kg',
 'par_seca_masa_beztluszcz_proc',
 'par_seca_wsk_masy_beztluszcz_kg_m2',
 'par_seca_brzuszna_tk_tluszczowa',
 'par_seca_bmi',
 'par_seca_wys_ciala',
 'par_seca_masa_ciala',
 'liczba_zebow',
 'PUW_P',
 'PUW_U',
 'PUW_W',
 'PUW_SUMA',
 'API_POW_Z_PLYTKA',
 'API_BADANE_POW',
 'API_18',
 'API_17',
 'API_16',
 'API_15',
 'API_14',
 'API_13',
 'API_12',
 'API_11',
 'API_21',
 'API_22',
 'API_23',
 'API_24',
 'API_25',
 'API_26',
 'API_27',
 'API_28',
 'API_48',
 'API_47',
 'API_46',
 'API_45',
 'API_44',
 'API_43',
 'API_42',
 'API_41',
 'API_31',
 'API_32',
 'API_33',
 'API_34',
 'API_35',
 'API_36',
 'API_37',
 'API_38',
 'PlI_18',
 'PlI_17',
 'PlI_16',
 'PlI_15',
 'PlI_14',
 'PlI_13',
 'PlI_12',
 'PlI_11',
 'PlI_21',
 'PlI_22',
 'PlI_23',
 'PlI_24',
 'PlI_25',
 'PlI_26',
 'PlI_27',
 'PlI_28',
 'PlI_48',
 'PlI_47',
 'PlI_46',
 'PlI_45',
 'PlI_44',
 'PlI_43',
 'PlI_42',
 'PlI_41',
 'PlI_31',
 'PlI_32',
 'PlI_33',
 'PlI_34',
 'PlI_35',
 'PlI_36',
 'PlI_37',
 'PlI_38',
 'GI_18',
 'GI_17',
 'GI_16',
 'GI_15',
 'GI_14',
 'GI_13',
 'GI_12',
 'GI_11',
 'GI_21',
 'GI_22',
 'GI_23',
 'GI_24',
 'GI_25',
 'GI_26',
 'GI_27',
 'GI_28',
 'GI_48',
 'GI_47',
 'GI_46',
 'GI_45',
 'GI_44',
 'GI_43',
 'GI_42',
 'GI_41',
 'GI_31',
 'GI_32',
 'GI_33',
 'GI_34',
 'GI_35',
 'GI_36',
 'GI_37',
 'GI_8',
 'SBI_18',
 'SBI_17',
 'SBI_16',
 'SBI_15',
 'SBI_14',
 'SBI_13',
 'SBI_12',
 'SBI_11',
 'SBI_21',
 'SBI_22',
 'SBI_23',
 'SBI_24',
 'SBI_25',
 'SBI_26',
 'SBI_27',
 'SBI_28',
 'SBI_48',
 'SBI_47',
 'SBI_46',
 'SBI_45',
 'SBI_44',
 'SBI_43',
 'SBI_42',
 'SBI_41',
 'SBI_31',
 'SBI_32',
 'SBI_33',
 'SBI_34',
 'SBI_35',
 'SBI_36',
 'SBI_37',
 'SBI_38',
 'CPI_18',
 'CPI_17',
 'CPI_16',
 'CPI_15',
 'CPI_14',
 'CPI_13',
 'CPI_12',
 'CPI_11',
 'CPI_21',
 'CPI_22',
 'CPI_23',
 'CPI_24',
 'CPI_25',
 'CPI_26',
 'CPI_27',
 'CPI_28',
 'CPI_48',
 'CPI_47',
 'CPI_46',
 'CPI_45',
 'CPI_44',
 'CPI_43',
 'CPI_42',
 'CPI_41',
 'CPI_31',
 'CPI_32',
 'CPI_33',
 'CPI_34',
 'CPI_35',
 'CPI_36',
 'CPI_37',
 'CPI_38',
 'API_SUMA',
 'API_proc',
 'cpi.suma',
 'GI.suma',
 'SBI.suma',
 'PlI.suma',
 'cpi',
 'gi',
 'sbi',
 'pli',
 'cpi_kat',
 'gi_kat',
 'sbi_kat',
 'pli_kat',
 'liczba_zebow_kat',
 'api_proc_kat',
 'cpi_z',
 'gi_z',
 'sbi_z',
 'pli_z',
 'API_proc_z',
 'cdi',
 'hig_myje_zeby_ile',
 'kombinacja',
 'hig_jedz_slodycz_teraz_U',
 'hig_jedz_slodkie_napoje_teraz_U',
 'hig_jedz_owoce_teraz_U',
 'hig_jedz_slodka_kawa_teraz_U',
 'hig_jedz_slodycz_20_40_U',
 'hig_jedz_slodkie_napoje_20_40_U',
 'hig_jedz_owoce_20_40_U',
 'hig_jedz_slodka_kawa_20_40_U',
 'hig_jedz_slodka_guma_20_40_U',
 'hig_zab_piaskowanie_U',
 'hig_zab_usu_kamienia_U',
 'pom_wys_ciala',
 'pom_wys_kolan',
 'pom_obw_szyji',
 'pom_obw_brzuch',
 'pom_obw_bioder',
 'pom_obw_klatki',
 'pom_sze_ramion',
 'pom_sze_bioder',
 'pom_sze_twarzy',
 'pom_sze_zuchwy',
 'pom_wys_twarzy',
 'pom_wys_twarzy_fwhr',
 'pom_obw_ram_p',
 'pom_obw_ram_l',
 'pom_fald_podlop_p',
 'pom_fald_podlop_l',
 'pom_fald_ram_p',
 'pom_fald_ram_l',
 'pom_sila_reka_p',
 'pom_sila_reka_l',
 'pom_sila_grzebiet',
 'pom_sze_nadgar_p',
 'pom_sze_nadgar_l',
 'pom_pal_p_2',
 'pom_pal_l_2',
 'pom_pal_p_3',
 'pom_pal_l_3',
 'pom_pal_p_4',
 'pom_pal_l_4',
 'pom_pal_p_5',
 'pom_pal_l_5',
 'hsCRP',
 'sIgA',
 'ank_zdro_alko_U',
 'ank_zdro_leki_U',
 'ank_zdro_chor_przew_U',
 'ank_zdro_chor_przew_cukrz',
 'ank_zdro_leki_cukrzyca_D',
 'par_hg_glikowana_norma',
 'par_ob_norma']

In [28]:
df[]

Warning: Total number of columns (621) exceeds max_columns (20). Falling back to pandas display.

,Unnamed: 0,id,hig_sub_oc_zebow,hig_sub_oc_zebow_dych,hig_sub_oc_dziasel,hig_sub_oc_dziasel_dych,hig_kiedy_myje_zeby,hig_myje_zeby_od_razu_po_przebudzeniu,hig_myje_zeby_przed_polożeniem_się_spać,hig_myje_zeby_po_każdym_dużym_posilku,...,pom_pal_l_5,hsCRP,sIgA,ank_zdro_alko_U,ank_zdro_leki_U,ank_zdro_chor_przew_U,ank_zdro_chor_przew_cukrz,ank_zdro_leki_cukrzyca_D,par_hg_glikowana_norma,par_ob_norma
0,0,1,3.0,NizszaOcena,4.0,NizszaOcena,"Od razu po przebudzeniu,Po każdym dużym posiłk...",1.0,1.0,1.0,...,63.110,NaN,NaN,4 razy w tygodniu i częściej,NIE,Brak,Brak,0,1.0,1.0
1,1,2,4.0,NizszaOcena,6.0,WyzszaOcena,"Od razu po przebudzeniu,Przed położeniem się spać",1.0,1.0,0.0,...,67.585,NaN,NaN,nigdy,NIE,Brak,Brak,0,1.0,1.0
2,2,3,5.0,WyzszaOcena,5.0,WyzszaOcena,"Przed wyjściem z domu,Przed położeniem się spać",0.0,1.0,0.0,...,65.110,NaN,NaN,raz w miesiącu lub rzadziej,NIE,Brak,Brak,0,1.0,1.0
3,3,4,5.0,WyzszaOcena,4.0,NizszaOcena,"Od razu po przebudzeniu,Przed położeniem się spać",1.0,1.0,0.0,...,59.060,NaN,NaN,raz w miesiącu lub rzadziej,NIE,Brak,Brak,0,1.0,1.0
4,4,5,5.0,WyzszaOcena,5.0,WyzszaOcena,"Od razu po przebudzeniu,Po każdym dużym posiłk...",1.0,1.0,1.0,...,61.945,0.829224,2032.905,raz w miesiącu lub rzadziej,TAK,Brak,Brak,0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,206,207,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,63.570,0.400810,319.200,nigdy,TAK,Brak,Brak,0,1.0,1.0
207,207,208,5.0,WyzszaOcena,4.0,NizszaOcena,"Przed wyjściem z domu,Przed położeniem się spać",0.0,1.0,0.0,...,60.245,0.732794,4136.990,raz w miesiącu lub rzadziej,NIE,Brak,Brak,0,1.0,1.0
208,208,209,4.0,NizszaOcena,3.0,NizszaOcena,Przed położeniem się spać,0.0,1.0,0.0,...,62.605,0.465587,NaN,raz w miesiącu lub rzadziej,NIE,Brak,Brak,0,1.0,1.0
209,209,210,4.0,NizszaOcena,4.0,NizszaOcena,Po każdym dużym posiłku,0.0,0.0,1.0,...,64.595,1.080972,862.020,raz w miesiącu lub rzadziej,NIE,Refluks/GERD,Refluks (od 20 lat),0,1.0,1.0
210,210,211,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,61.610,5.056680,1688.610,4 razy w tygodniu i częściej,TAK,Nadciśnienie tętnicze,Nadciśnienie (1 rok),0,1.0,0.0

In [31]:
# Tworzenie kolumny dummy dla obecności oceny zębów
df['hig_sub_oc_zebow_dummy'] = df['hig_sub_oc_zebow'].notna().astype(int)

# Sprawdzenie wyników
print("Podsumowanie obecności danych w 'hig_sub_oc_zebow':")
print(df['hig_sub_oc_zebow_dummy'].value_counts())
display(df[['hig_sub_oc_zebow', 'hig_sub_oc_zebow_dummy']].head(10))

Podsumowanie obecności danych w 'hig_sub_oc_zebow':
hig_sub_oc_zebow_dummy
1    154
0     57
Name: count, dtype: int64

   hig_sub_oc_zebow  hig_sub_oc_zebow_dummy
0               3.0                       1
1               4.0                       1
2               5.0                       1
3               5.0                       1
4               5.0                       1
5               NaN                       0
6               5.0                       1
7               NaN                       0
8               4.0                       1
9               NaN                       0